services:
  backend-service:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend-service-container
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis:6379
      - REDIS_URL_2=redis2:6379
      - DATABASE_URL=postgresql://user:vicecity@postgres-db:5432/postgres
    depends_on:
      - redis
      - redis2
      - postgres-db
  
  orderbook-service:
    build:
      context: ./orderbook/
      dockerfile: Dockerfile
    container_name: orderbook-service-container
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis:6379
      - REDIS_URL_2=redis2:6379
      - DATABASE_URL=postgresql://user:vicecity@postgres-db:5432/postgres
    depends_on:
      - redis
      - redis2
    volumes:
      - orderbook-data:/app/data/db.json 
    

  redis:
    image: redis:alpine
    container_name: redis-container1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis2:
    image: redis:alpine
    container_name: redis-container2
    ports:
      - "6380:6379"
    volumes:
      - redis2-data:/data

  postgres-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=vicecity
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/data
    container_name: postgres-container


volumes:
  redis-data:
    driver: local
  redis2-data:
    driver: local
  postgres-data:
    driver: local
  orderbook-data: